### ISSUE TITLE
No directory created when collecting a scene

### ISSUE THREAD

**Issue by EnriqueSolarte** [EnriqueSolarte/hm3d_data_collector#1]
![Image](https://github.com/user-attachments/assets/9b1ff760-398e-4910-b926-bdc8d7b2fc7b)

This use was reported when collecting a scene using the version `hm3d_data_collector v2.0`. This issue was due to the inherent order in Hydra when loading default configurations. 

**Solution:**
Switch the order of the default configurations in the `cfg.yaml` -> `example/cfg.ymal`

```yaml

hydra:
  searchpath:
    - ${oc.env:HM3D_DATA_COLLECTOR_CFG_DIR}
    - ${oc.env:GEOM_UTILS_CFG_DIR}

defaults:
  - general # <----- This must be first
  - habitat_sim
  - hm_data
  - _self_


```
The configuration `general` is loaded from `GEOM_UTILS_CFG_DIR` (_installed by git+https://github.com/EnriqueSolarte/geometry_perception_utils.git@latest_). This configuration defines `log_dir` (directory to save logs) in a default directory. Then `hm_data`configuration (loaded from `HM3D_DATA_COLLECTOR_CFG_DIR`) overwrites this value at the directory where the collected scene is stored.  Note that the log directory is defined outside of the scene directory if a different order is used.  Also, note that the `log_dir` is created automatically by Hydra at runtime, so if the log_dir and the scene directory are well-defined, then the scene directory is created automatically.
